Name:           ros-melodic-message-relay
Version:        0.0.2
Release:        1%{?dist}
Summary:        ROS message_relay package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-actionlib-msgs
Requires:       ros-melodic-controller-manager-msgs
Requires:       ros-melodic-diagnostic-msgs
Requires:       ros-melodic-gazebo-msgs
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-map-msgs
Requires:       ros-melodic-move-base-msgs
Requires:       ros-melodic-multimaster-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-robot-localization
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rosgraph-msgs
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-shape-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-std-srvs
Requires:       ros-melodic-stereo-msgs
Requires:       ros-melodic-tf2-msgs
Requires:       ros-melodic-trajectory-msgs
Requires:       ros-melodic-visualization-msgs
BuildRequires:  python-cheetah
BuildRequires:  ros-melodic-actionlib-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-controller-manager-msgs
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-gazebo-msgs
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-map-msgs
BuildRequires:  ros-melodic-move-base-msgs
BuildRequires:  ros-melodic-multimaster-msgs
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-robot-localization
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rosgraph-msgs
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-shape-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-std-srvs
BuildRequires:  ros-melodic-stereo-msgs
BuildRequires:  ros-melodic-tf2-msgs
BuildRequires:  ros-melodic-trajectory-msgs
BuildRequires:  ros-melodic-visualization-msgs

%description
Package to programmatically spawn message, service, and action relays. To add
support for a message/service dependency, please add to the build dependencies
in package.xml and CMakeLists.txt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Jul 16 2019 Paul Bovbel <pbovbel@clearpath.ai> - 0.0.2-1
- Autogenerated by Bloom

